spring:
  application:
    name: message-service

  config:
    import: optional:configserver:http://config-service.config.svc.cluster.local:8888

  cloud:
    config:
      name: message-service
      label: main
      fail-fast: true


profiles:
  active: cloud