spring:
  application:
    name: message-service

  config:
    activate:
      on-profile: cloud
    import: "optional:configserver:http://config-service.config.svc.cluster.local:8888"

logging:
  level:
    org.springframework.boot.context.config: debug